### PR TITLE
Fixes #49: parse multibyte characters

### LINKED ISSUE #49: Multibyte characters in source code
(Originally reported at yihui/knitr#988) When there are multibyte characters in the source code, `parse_all()` fails to extract the correct source:

```r
parse_all('ϱ <- 1# g / ml')
#             src   expr
# 0 ϱ <- 1 g / ml ϱ <- 1
parse_all('x <- "中文" # hello')
#               src        expr
# 0 x <- "中文"ello x <- "中文"
```

This is because `srcref` gives the column positions based on _bytes_ instead of column numbers (characters), e.g. the first example above has an expression from the 1st to 7th byte. Unfortunately, `getSrcRegion()` is based on column numbers, so `get_region()` in `parse_all()` extracts the incomplete source code from srcfile.

I'm pretty sure this had worked before. There must be a change in a certain version of R that I did not notice.

### PR DESCRIPTION
**Pull request by yihui**
@hadley Since this is a basically rewrite of `parse_all()`, I hope you can take a look first. I have tested it as thoroughly as I can. The reason of the bug has been explained in #49. This fix basically ignores column numbers in `srcref`, so we don't have to think about chars vs bytes.

After this fix, `parse_all()` can be ~4 times faster, although performance is not the goal.

### CODE REVIEW

File: R/parse.r [hunk 1]
```diff
@@ -12,107 +12,85 @@ parse_all <- function(x) UseMethod("parse_all")
 
 #' @export
 parse_all.character <- function(x) {
-  x <- unlist(str_split(x, "\n"), recursive = FALSE, use.names = FALSE)
+
+  op <- options(stringsAsFactors = FALSE)
```
Comment (hadley) [inline R/parse.r]: This saves some typing, and is safe because you have `on.exit` but it makes the code harder to read because you need to understand more about the sequence of operations.

File: R/parse.r [hunk 2]
```diff
@@ -12,107 +12,85 @@ parse_all <- function(x) UseMethod("parse_all")
...
-    lines <- strsplit(string, "(?<=\n)", perl=TRUE)[[1]]
-    n <- length(lines)
-    if (n == 0) {
-      lines <- ""
-      n <- 1
-    }
+  srcref <- attr(exprs, "srcref", exact = TRUE)
 
+  # Stard/End line numbers of expressions
+  pos <- as.data.frame(t(sapply(srcref, unclass))[, c(1, 3), drop = FALSE])
```
Comment (hadley) [inline R/parse.r]: `sapply()` is dangerous - maybe it could be replaced just with `lapply()` ? (or is that in the wrong direction?)

**Comment by hadley** [comment]
I can't really follow the code (either my version or your version), and it's not obvious what you changed to fix multibyte. So my comments probably aren't that useful, sorry.

File: R/parse.r (hunk 2 above)
Comment (yihui) [inline R/parse.r]: I was just copying your code. Now I have changed it to `lapply()`.

**Comment by yihui** [comment]
That is fine. I will drive the bus by myself. Thanks!
